config/routes.rb
Rails.application.routes.draw do
  root to: 'page#index'
  resources :articles
  resources :todos
  get 'signup', to: 'users#new'
  get 'login', to: 'session#new'
  post 'login', to: 'session#create'
  get 'logout', to: 'session#destroy'
  resources :users, except: [:new]
  resources :categories, except: [:destroy]
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/article.rb
class Article < ApplicationRecord
  belongs_to :user 

   validates :title, presence: true, length: {minimum: 3, maximum: 25}
   validates :description, presence: true, length: {minimum: 10, maximum: 200}


end

app/models/category.rb
class Category < ApplicationRecord
validates :name, presence: true, length: {minimum: 3, maximum: 25}
validates_uniqueness_of :name
end

app/models/todo.rb
class Todo < ApplicationRecord
 validates :title, presence: true
 validates :description, presence: true





end

app/models/user.rb
class User < ApplicationRecord
  before_save { self.email = email.downcase }
  has_many :articles, dependent: :destroy
  validates :username, presence: true,
                        uniqueness: { case_sensitive: false } ,
                        length: {minimum: 3, maximum: 25}

  VALID_EMAIL_REGEX =    /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i                      

  validates :email, presence: true, 
                       uniqueness: { case_sensitive: false } , 
                       length: { maximum: 105},
                       format: {with: VALID_EMAIL_REGEX}
 
  has_secure_password                     




end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

helper_method :current_user, :logged_in?

def current_user
 @current_user ||= User.find(session[:user_id]) if session[:user_id] 

end 


def logged_in?
    !!current_user
end

def require_user
    if !logged_in?
        flash[:alert] = "you must be logged in to perform this action"
        redirect_to login_path
    end

end

end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: %i[ show edit update destroy ]
  before_action :require_user, except: [:index , :show]
 before_action :require_same_user, only: [:edit, :update, :destroy]

  # GET /articles or /articles.json
  def index
    @articles = Article.paginate(page: params[:page], per_page: 5)
  end

  # GET /articles/1 or /articles/1.json
  def show
  end

  # GET /articles/new
  def new
    @article = Article.new
  end

  # GET /articles/1/edit
  def edit
  end

  # POST /articles or /articles.json
  def create
    @article = Article.new(article_params)
    @article.user = current_user

    respond_to do |format|
      if @article.save
        format.html { redirect_to article_url(@article), notice: "Article was successfully created." }
        format.json { render :show, status: :created, location: @article }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /articles/1 or /articles/1.json
  def update
    respond_to do |format|
      if @article.update(article_params)
        format.html { redirect_to article_url(@article), notice: "Article was successfully updated." }
        format.json { render :show, status: :ok, location: @article }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /articles/1 or /articles/1.json
  def destroy
    @article.destroy

    respond_to do |format|
      format.html { redirect_to articles_url, notice: "Article was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_article
      @article = Article.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def article_params
      params.require(:article).permit(:title, :description)
    end
    def require_same_user
      if current_user != @article.user && !current_user.admin?
        flash[:alert] = "you can only edit or delete your own Article"
        redirect_to @article
      end
    end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

def new
  @category = Category.new
end


def index
  @categories = Category.all
end 


def show
  @category = Category.find(params[:id])
end 


def create 
@category = Category.new(category_params)
if @category.save
     flash[:notice] = "you have successfully created category"
     redirect_to @category
else
   render 'new'
 end

end 

private

def category_params 
  params.require(:category).permit(:name)

end


end

app/controllers/page_controller.rb
class PageController < ApplicationController


  def index
    redirect_to articles_path if logged_in?
  end
end

app/controllers/session_controller.rb
class SessionController < ApplicationController


  def new

  end

  def create 
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      session[:user_id]  = user.id
      flash[:notice] = "Logged in Successfully"
      redirect_to user
    else
      flash.now[:alert] = "Email/password wrong"
      render 'new'
    end

  end

  def destroy 
    session[:user_id] = nil
    flash[:notice] = "Logged out successfully"
    redirect_to root_path
  end

end

app/controllers/todos_controller.rb
class TodosController < ApplicationController
    before_action :set_todo, only: [:show, :edit, :update, :destroy]


  def index 
    @todos = Todo.all
  end 

  def show      
  end

 def new
   @todo = Todo.new
 end

  def edit 
  end
  
  def update    
      if @todo.update(todo_params)   
         flash[:notice] = "Article updated successfully"
          redirect_to @todo
      else
         render 'edit' 
      end
       
  end 

 def create 
     @todo =Todo.new(todo_params)
    if  @todo.save
      flash[:notice] = "Article created successfully"
      redirect_to @todo
    else
      render 'new' 
    end 
 end

 def destroy
   @todo.destroy
   redirect_to todos_path
 end

private 

 def set_todo
   @todo =Todo.find(params[:id])
 end

 def todo_params
    params.require(:todo).permit(:title, :description, :feedback)
 end

end     

app/controllers/users_controller.rb
class UsersController < ApplicationController 
  before_action :set_users, only: %i[ show edit update destroy ]
  before_action :require_user, only: [:edit, :update]
  before_action :require_same_user, only: [:edit, :update, :destroy]

def new
  @user= User.new
end

def edit

end

def index
    @users=User.all.paginate(page: params[:page], per_page: 4)
end

def update
   
    if @user.update(user_params)
      flash[:notice] = "successfully updated"
      redirect_to @user
    else
      render 'edit'

    end
  end
def show
  @articles = @user.articles.paginate(page: params[:page], per_page: 4)
end



def create
  @user = User.new(user_params)
  if @user.save
     session[:user_id]  = @user.id
    flash[:notice] = "Welcome to the Alpha Blog #{@user.username} , you are successfully signed_up"
    redirect_to articles_path
  else
    render 'new'
  end
end

def destroy
 @user.destroy
 session[:user_id] = nil if @user == current_user
 flash[:notice] = "Account and all associated articles successfully deleted"
 redirect_to articles_path

end

 private
  def user_params
     params.require(:user).permit( :username, :email, :password)
  end

  def set_users
      @user =User.find(params[:id]) 

  end

  def require_same_user
  if current_user != @user  && !current_user.admin?
    flash[:alert] = "you can only edit or delete your own profile"
    redirect_to users_path
  end
end

end

app/helpers/application_helper.rb
module ApplicationHelper
  def gravatar_for(user, options = {size: 80})
  email_address =user.email.downcase
  hash = Digest::MD5.hexdigest(email_address)
  size =options[:size]
  gravatar_url = "https://www.gravatar.com/avatar/#{hash}?s=#{size}"
  image_tag(gravatar_url, alt: user.username)
end





end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/category_helper.rb
module CategoryHelper
end

app/views/articles/_article.html.erb
<p style="color: green"><%= notice %></p>

<div id="articles">
  <% @articles.each do |article| %>
  <%if article.user%>
  <p>
 by : <%= link_to article.user.username, user_path(article.user) %> </p>

<%end%> 
  <div id="<%= dom_id article %>">
  <p>
    <strong>Title:</strong>
    <%= article.title %>
  </p>

  <p>
    <strong>description:</strong>
    <%= article.description %>
  </p>

</div>

<% if  logged_in? && (article.user == current_user || current_user.admin?) %>

<%= button_to "Delete",  article, method: :delete%>  
<button> <%= link_to "Edit",  edit_article_path(article) %> </button>
<button> <%= link_to "View", article %> </button> 

<%else%>
 <button>
   <%= link_to "View", article %>
 </button>

<%end%>
   
   
   
    
</div>

 <% end %>

app/views/articles/_form.html.erb
<%= form_with(model: article) do |form| %>
<%= render 'shared/errors' , obj: @article %>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_field :description %>
  </div>
<br>
  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/articles/edit.html.erb
<h1>Editing article</h1>

<%= render "form", article: @article %>

<br>
<%= link_to "New article", new_article_path %>
<div>
  <%= link_to "Show this article", @article %> |
  <%= link_to "Back to articles", articles_path %>
</div>

app/views/articles/index.html.erb
<h1> Listing All Articles</h1>
 <%if logged_in? %>

<h4> you are logged in as :<%= "(Admin)"if current_user.admin?  %>  <%= link_to  current_user.username, user_path(current_user) %> </h4>
<button>
<%= link_to  'Logout', logout_path, method: :delete %></button>
<button><%= link_to "New article", new_article_path %></button>

<button><%= link_to "New Category", new_category_path %></button>

<%else%>
<button>
<%= link_to "Login", login_path %> </button>
 <button><%= link_to "Signup", signup_path %></button>

<%end%>
<h2><%= link_to "All Users", users_path %></h2>


<%=render 'article'%>

<div class="digg_pagination">
    <div class="page_info">
      <%= page_entries_info @articles %>
    </div>
    <%= will_paginate @articles, :container => false %>
  </div>

app/views/articles/new.html.erb
<h1>New article</h1>
<% if logged_in? %>
<%= render "form", article: @article %>
<%end%>
<br>

<div>
  <%= link_to "Back to articles", articles_path %>
</div>

app/views/articles/show.html.erb
<p style="color: green"><%= notice %></p>
 <%if logged_in? %>
<button>
<%= link_to  'Logout', logout_path, method: :delete %>
</button>
<%else%>
<button>
<%= link_to "Login", login_path %> </button>
 <button><%= link_to "Signup", signup_path %></button>
 

<%end%>
 
<p> <strong> User : </strong> <%= @article.user.username if @article.user%> </p>
 <div id="<%= dom_id @article %>">
 <p>
   <strong>Title:</strong>
   <%= @article.title %>
 </p>
 <p>
   <strong>description:</strong>
   <%= @article.description %>
 </p>
 </div>
 
</div>
 
<%if logged_in? && (@article.user == current_user || current_user.admin?)%>
<div>
  <%= link_to "All Articles", articles_path %>
  <%= link_to "Edit", edit_article_path(@article) %> 
  <%= button_to "Delete", @article, method: :delete %>
</div>
<%else%>
 <div> <%= link_to "Back to articles", articles_path %></div>
<%end%>

app/views/categories/index.html.erb
<h1> index </h1>
<p style="color: green"><%= notice %></p>
<% @categories.each do |category| %>
<p>
  <strong>Name:</strong>
  <%= category.name%>
  <%= link_to "View", category %>
</p>
<%end%>
 <%= link_to "Back to Articles", articles_path %>

app/views/categories/new.html.erb
<h1>Create New Category<h1>
<%= render 'shared/errors' , obj: @category %>
<%= form_with(model: @category) do |form| %>


  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/categories/show.html.erb
<h3> Category Name :<%= @category.name%> </h3>
 <%= link_to "Back to Articles", articles_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TraningApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
  <%flash.each do |name, msg| %>
 <h3 style = "color: green"> <%=msg%> </h3>
  <%end%>
 
  <%= yield %>
  </body>
</html>

app/views/page/index.html.erb
<h1> Front page </h1>

 <%if logged_in? %>
 <h4> you are logged in as :<%= link_to  current_user.username, user_path(current_user) %> </h4>
 <%= link_to "Articles", articles_path%>
<button>
<%= link_to  'Logout', logout_path, method: :delete %>

</button>
<%else%>

<span> You can only view articles :</span>
<%= link_to "Enter without login/signup", articles_path %>
<h4> For creating an Article  you need to login or signup </h3>
<button><%= link_to "Login", login_path %> </button>
<button><%= link_to "Signup", signup_path %></button>


<%end%>
 

app/views/session/new.html.erb
<h1>login</h1>

<%= form_with(scope: :session, url: login_path) do |form| %>

  <div>
    <%= form.label :email, style: "display: block" %>
    <%= form.email_field :email , placeholder: "Enter Email address" %>
  </div>
  <div>
  <%= form.label :password, style: "display: block" %>
  <%= form.password_field :password , placeholder: "Enter your Password" %>
</div>
<br>
  <div>
    <%= form.submit "Login" %>
  </div>
<% end %>
<h3> if you do not have account created : </h3>
<button><%= link_to "Signup ", signup_path %></button>

app/views/shared/_errors.html.erb
<% if obj.errors.any? %>
  <div style="color: red">
    <h3>following errors prevented  this <%= obj.class.name.downcase %> from being saved:</h3>
    <ul>
      <% obj.errors.full_messages.each do |error| %>
        <li><%= error %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/todos/edit.html.erb
<h1> Edit Todo </h1>

<%= form_with(model: @todo, local: true)  do |f| %>
  <% if @todo.errors.any? %>
    <h2 style="color: red"> <%= pluralize(@todo.errors.count, "error") %>prohibited this article from being saved :</h2>

   <ul>
    <% @todo.errors.full_messages.each do |msg| %>
      <li  style="color: red"> <%= msg %>  </li>
    <% end %>
   </ul>
  <% end %>

<p> <%= f.label :title%> 
<br/>
 <%=f.text_field :title %>
</p>

<p>
<%= f.label :description%>
<br/>
<%= f.text_area :description%>
</p>
<p>
<%= f.label :feedback%>
<br/>
<%= f.text_area :feedback%>
</p>
<p>
<%= f.submit %>
</p>


<% end %>

app/views/todos/index.html.erb
<h1>All Todos</h1>

<h3> <%=link_to 'Create New Todo' ,  new_todo_path(@todo)%> </h3>
<table style = "border: 1px solid white"> 
<thead>
 <tr>
    <th> <strong> Title  </th>
    <th>  <strong> Description  </th>
    <th>  <strong> Feedback  </th>
    <th colspan = "3"> Actions </th>
 </tr>
</thead>
<tbody>
<% @todos.each do |t| %>
  <tr> 
    <td> <%= t.title %>  </td>
    <td> <%= t.description %> </td>
    <td> <%= t.feedback %> </td>
    <td> <%=link_to 'Show', todo_path(t)%> </td>
    <td> <%=link_to 'Edit' ,  edit_todo_path(t)%> </td>
    <td> <%= button_to 'Delete', t, method: :delete, data: {confirm: "Are you sure"} %> </td>
  </tr>
  <%end%>
<tbody>

</table>

app/views/todos/new.html.erb
<h1> Create New Todo </h1>

<%= form_with(model: @todo)  do |f| %>
  <% if @todo.errors.any? %>
    <h2 style="color: red"> <%= pluralize(@todo.errors.count, "error") %>prohibited this article from being saved :</h2>

   <ul>
    <% @todo.errors.full_messages.each do |msg| %>
      <li  style="color: red"> <%= msg %>  </li>
    <% end %>
   </ul>
  <% end %>

<p> <%= f.label :title%> 
<br/>
 <%=f.text_field :title %>
</p>

<p>
<%= f.label :description%>
<br/>
<%= f.text_area :description%>
</p>
<p>
<%= f.label :feedback%>
<br/>
<%= f.text_area :feedback%>
</p>
<p>
<%= f.submit %>
</p>


<% end %>

app/views/todos/show.html.erb
<h1> todo </h1>
<p> <strong> Todo: </strong><%= @todo.title %> </p>
<p> <strong>  Description:</strong>  <%= @todo.description %> </p>
<p> <strong>  Feedback:  </strong>   <%= @todo.feedback %> </p>

  <%=link_to 'Edit' ,  edit_todo_path(@todo)%> 
 <%= link_to "Back to todos", todos_path %> 
  <%= button_to 'Delete', @todo, method: :delete,  data: {confirm: "Are you sure ?" } %> 

app/views/users/_form.html.erb
<%= render 'shared/errors' , obj: @user %>

<%= form_with(model: user) do |form| %>

  <div>
    <%= form.label :username, style: "display: block" %>
    <%= form.text_field :username , placeholder: "Enter username" %>
  </div>

  <div>
    <%= form.label :email, style: "display: block" %>
    <%= form.email_field :email , placeholder: "Enter Email address" %>
  </div>
  <div>
  <%= form.label :password, style: "display: block" %>
  <%= form.password_field :password , placeholder: "Choose Password" %>
</div>
<br>
  <div>
    <%= form.submit(@user.new_record? ?  "Signup" : "Update Account") %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Edit your Profile</h1>
</br>
<%= render "form", user: @user %>

app/views/users/index.html.erb
<h1>list of all users</h1>
 <%if logged_in? %>
 <h4> you are logged in as :<%= link_to  current_user.username, user_path(current_user) %> </h4>
<button>
<%= link_to  'Logout', logout_path, method: :delete %> </button>



<%else%>
<button>
<%= link_to "Login", login_path %> </button>
 <button><%= link_to "Signup", signup_path %></button>
 
<%end%>
 
  <% @users.each do |user| %>
  <h2> <%= user.username%> </h2>
  <p><%=pluralize(user.articles.count, "article")%></p>

  <%=gravatar_for user, size: 200%>
  <div>
  <%if logged_in? && (user.username == current_user.username || current_user.admin?)%>
  <p>
   <%= button_to "Delete", user_path(user), method: :delete, data: { confirm: "Are you sure?" } %>
  <%= link_to "Edit profile", edit_user_path(user) %> 
 
 
  <%end%>
  <%= link_to "Show profile", user %> </p>
  
  </div>
  
  <%end%>
 </div>
 <%= will_paginate @users, :container => false %>
 </div>

app/views/users/new.html.erb
<h1>sign_up</h1>
</br>
<%= render "form", user: @user %>

app/views/users/show.html.erb
<h1 ><%= current_user.username %>'s profile </h1>


<%=gravatar_for @user, size: 200%>
<div>
<%if logged_in? && @user.username == (current_user.username || current_user.admin?)%>

<button>
<%= link_to  'Logout', logout_path, method: :delete %>
</button> 
<button>
<%= link_to "New article", new_article_path %>
</button>
<button>
<%= link_to "Edit profile", edit_user_path(@user) %> 
</button>
<button> <%= link_to "Back to articles", articles_path %>
</button>
<%else%>
<button> <%= link_to "Back to articles", articles_path %> </button>
<%end%>

</div>
<h3 ><%= @user.username %>'s Articles </h3>
<%= render 'articles/article' %>
 </div>
 <%= will_paginate @articles, :container => false %>
 </div>